# Generated by Django 3.2.6 on 2023-06-02 20:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('isbn', models.BigIntegerField(default=0, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(13)])),
                ('judul', models.CharField(max_length=180)),
                ('stok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('primary_id', models.AutoField(primary_key=True, serialize=False)),
                ('ktp', models.BigIntegerField()),
                ('nama', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('tanggal_pinjam', models.DateTimeField(auto_now_add=True)),
                ('tanggal_deadline', models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=django.db.models.expressions.ExpressionWrapper(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('tanggal_pinjam'), '+', django.db.models.expressions.Value(datetime.timedelta(days=30))), output_field=models.DurationField()))])),
                ('tanggal_pengembalian', models.DateTimeField()),
                ('dikembalikan', models.BooleanField(default=False)),
                ('telat', models.BooleanField(default=False)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
            ],
        ),
    ]
