# Generated by Django 3.2.6 on 2023-06-02 21:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='isbn',
            field=models.BigIntegerField(default=1000000000000, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000000000), django.core.validators.MaxValueValidator(9999999999999)]),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='buku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_pengembalian',
            field=models.DateTimeField(blank=True),
        ),
    ]
