# Generated by Django 3.2.6 on 2023-06-02 21:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_alter_peminjaman_tanggal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_deadline',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=django.db.models.expressions.F('tanggal_pinjam'), message='End date must be greater than or equal to start date'), django.core.validators.MaxValueValidator(limit_value=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('tanggal_pinjam'), '+', django.db.models.expressions.Value(datetime.timedelta(days=30))), message='End date must be within 30 days of start date')]),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_pinjam',
            field=models.DateField(auto_now_add=True),
        ),
    ]
