# Generated by Django 3.2.6 on 2023-06-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0007_alter_peminjaman_tanggal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_deadline',
            field=models.DateField(),
        ),
    ]
